### ISSUE TITLE
no longer works with latest prepack 0.2.38

### ISSUE THREAD

**Issue by Pyrolistical** [tunnckoCore/rollup-plugin-prepack#13]
This fork changed the API https://github.com/joseluisq/rollup-plugin-prepack-up, but uses the correct prepack api

**Comment by tunnckoCore** [comment]
Oh yea.. I just seen #12. I'l merge it and release/publish probably tomorrow.

@joseluisq why not just sent PR?

**Comment by Pyrolistical** [comment]
i don't see how #12 will fix the issue. The current code calls `prepack.prepack` which doesn't work, I think it needs to be changed to `prepack.prepackSources`

**Comment by tunnckoCore** [comment]
Why not, there is no `prepack` method anymore? Didn't used it recently and don't actively following it. But i can add someone to have access to the repo and npm.

**Comment by Pyrolistical** [comment]
They changed it to `Prepack.prepackSources([{filePath, fileContents, sourceMapContents}], options) // returns { code: string, map: SourceMap }`

See https://prepack.io/getting-started.html

**Comment by Pyrolistical** [comment]
Also I don't understand how this is suppose to work. I have rollup generating a UMD with the plugin stack:

 * rollup-plugin-node-resolve
 * rollup-plugin-commonjs
 * rollup-plugin-babel
 * prepack plugin using prepackSources
 * rollup-plugin-terser

But when I looked at what is passed into prepack and it already includes the UMD jazz. There's no way prepack would work, since UMD is fundamentally about figuring out the environment. Prepack needs to run after all the files are concat into one, but before its final iife/umd output

**Comment by joseluisq** [comment]
Hey guys, sorry for the confusion. 
The main reason because I had decided to fork was that I needed the plugin very urgent and I didn't see activity in this repo (at the fork moment) at least since the last year.

> @joseluisq why not just sent PR?

Sure, I can send a PR if you prefer. This #12 upgrade the dependency only.
Basically the Prepack API has changed:

- from: `prepack.prepack(source, options)`
- to: `prepack.prepackSources([{fileContents, filePath}], options)`

Tell me how can I help?

**Comment by tunnckoCore** [comment]
yea, I understand but not always time matter. In most of my repos everything is up to date and builds are passing without any changes for years. But yea.

Also could send another pr with the additional changes, so eventually was able to see your pr. Because some times we just miss the notifications, such as in this case.

Anyway :) PR is welcome, if not i'll do the changes. : )

Cheers

**Comment by joseluisq** [comment]
I just sent a PR with the API and dependency upgrades #14 
To say this PR is based on your current repository (in sync with your last changes) because my repo is quite different.
Let me know your feedback.

**Comment by tunnckoCore** [comment]
Sweet, thanks! :)

I requested some thoughts on the comments.

**Comment by gingur** [comment]
Any update on this? Couldn't you just pin the version of prepack to an older one until updated to support new?

**Comment by tunnckoCore** [comment]
prs welcome. but won't be able to publish on npm. or is there some non-terminal way? ;d

**Comment by tunnckoCore** [comment]
Published 1.1.0 stable.
